/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type IdentityAccountDetailsTransformer from '#app/identity/transformers/account_details_transformer'
import type UserTransformer from '#app/transformers/user_transformer'
import type InertiaMiddleware from '#app/middleware/inertia_middleware'

export namespace Data {
  export namespace Identity {
    export type AccountDetails = InferData<IdentityAccountDetailsTransformer>
    export namespace AccountDetails {
      export type Variants = InferVariants<IdentityAccountDetailsTransformer>
    }
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
