/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  identity: {
    Account: () => import('#app/identity/controllers/account_controller'),
    Login: () => import('#app/identity/controllers/login_controller'),
    Logout: () => import('#app/identity/controllers/logout_controller'),
    RegisterUser: () => import('#app/identity/controllers/register_user_controller'),
  },
}
