/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Orders {
  id: string;
  service_type: string;
  status: string;
  table_id: string | null;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  name: string | null;
  password: string;
  updated_at: Timestamp | null;
}

export interface DB {
  orders: Orders;
  users: Users;
}
